# Generated by Django 4.2 on 2023-12-01 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FaceSence', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(default=None, max_length=100)),
                ('dob', models.DateField(default=None)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='person/')),
                ('doj', models.DateField(default=None)),
                ('scan_image', models.ImageField(blank=True, null=True, upload_to='person-scan/')),
                ('person_email', models.CharField(default=None, max_length=256)),
                ('phoneno', models.CharField(default=None, max_length=13)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_person', models.CharField(default=None, max_length=20)),
            ],
            options={
                'unique_together': {('person_name', 'dob', 'doj')},
            },
        ),
    ]
