# Generated by Django 4.2 on 2023-12-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceSence', '0005_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FaceSence.signup')),
            ],
        ),
    ]
